### ISSUE TITLE
Apple M1 / darwin-arm64 build

### ISSUE THREAD

**Issue by shadiramadan** [falcosecurity/falcoctl#110]
**What would you like to be added**:
Apple M1 support via a darwin-arm64 build.

**Why is this needed**:
Apple M1 is arm based.

**Comment by leogr** [comment]
cc @alacuku

**Comment by alacuku** [comment]
Hi @shadiramadan,
the `darwin-arm64` build is available here: https://github.com/falcosecurity/falcoctl/actions/runs/2835316120. Note that the artifacts are retained just for 24 hours. 
Anyway, you should be able to build `falcoctl` from the source. Another alternative could be to wait for the next release.

**Comment by cpanato** [comment]
this is done already
/close
