### ISSUE TITLE
falcoctl registry login: enhancements

### ISSUE THREAD

**Issue by alacuku** [falcosecurity/falcoctl#134]
`falcoctl registry login` is used to login to a remote OCI registry. It accepts an argument which is the `domain name` of the registry and prompts the user to input its `username` and `password`:
```bash
$ falcoctl registry login my-regirstry.me
Username: my-username
Password: my-password
```
The credentials passed to the command are saved in `/home/user/.docker/config.json`. Subsequent calls to `falcoctl registry` commands will retrieve and use those credentials.

**What would you like to be added**:
The following flags/options should be added to the `login` command:
* `-p, --password`: registry password or identity token used for authentication;
* `-u, --username`: registry username used for authentication.

#### Command behavior
When no flags are passed to the `falcoctl registry login` command it must prompt the user for credentials. Otherwise, it will use the flag values and prompt the user for the missing ones.

**Why is this needed**:
This feature allows the `falcoctl registry login` to be scriptable.

**Comment by maxgio92** [comment]
I'm happy to work on this

**Comment by alacuku** [comment]
A community member is already working on this: https://kubernetes.slack.com/archives/CMWH3EH32/p1678019940711779

Could you please coordinate with him and let me know here?

Thanks!

**Comment by maxgio92** [comment]
Of course @alacuku ! :)
