### ISSUE TITLE
Revamping falcoctl: call for core maintainers

### ISSUE THREAD

**Issue by leogr** [falcosecurity/falcoctl#136]
Dear @falcosecurity/core-maintainers  :wave: 

As discussed recently, we have the intention of revamping this project. From what I understood until now, we have a short-term goal and a long-term dream.

In the short term, the idea is to make `falcoctl` the tool for installing plugins and rules artifacts (see https://github.com/falcosecurity/falcoctl/issues/103). Beyond that, I dream that this tool will replace the `falco-driver-loader` bash script in the future. 

## Short-term proposal

However, this ambitious plan needs your help. Unfortunately, I'm the only active maintainer of this repo, and as per our governance, we need at least two maintainers to make crucial decisions. For this reason, as a first step, I want to invite any willing core maintainer to step up (even temporarily) to become a maintainer of this repo ASAP.
(why core maintainers? see [this](https://github.com/falcosecurity/evolution/blob/main/REPOSITORIES.md#core-maintainers-duties-and-privileges)).  

**If you're interested, please comment** below. We will open a PR to vote on that once we have some volunteers.

Also, if nobody disagrees, I want to sponsor @alacuku and @loresuso as reviewers since they are doing an egregious job reworking this project and implementing the plugin/rules manager functionality.

## Next steps

The solution above will unblock the repository from a stagnant situation, but it's not enough for the project's future. Once the repo is functioning again, we should spend our effort seeking new contributors and maintainers (possibly increasing the maintainers' diversity).

One possible solution would be to start a structured mentoring program as described [here](https://github.com/falcosecurity/evolution/blob/main/MAINTAINERS_GUIDELINES.md#mentoring-programs).

**Comment by zuc** [comment]
I can volunteer at least for the short term ✋

**Comment by maxgio92** [comment]
I volunteer to help on revamping `falcoctl`, for short and long-term.

**Comment by FedeDP** [comment]
I can jump in as well :)

**Comment by leogr** [comment]
Since if I open the PR to vote on that, I won't be able to approve that, can I ask anyone else to open it? 
@jasondellaluce ?

**Comment by cpanato** [comment]
+1
let me know what do i need to do :)

**Comment by Issif** [comment]
this project will definitely looks like
![image](https://user-images.githubusercontent.com/4520100/188924944-a738cd5a-bad2-4a69-9b02-e5f6dc55cd8c.png)
:wink:
