### ISSUE TITLE
Actual dependencies are broken

### ISSUE THREAD

**Issue by fntlnz** [falcosecurity/falcoctl#14]
**What happened**:

When building falcoctl an error is given.

```
build github.com/falcosecurity/falcoctl: cannot load k8s.io/kube-deploy/cluster-api/api/cluster/v1alpha1: cannot find module providing package k8s.io/kube-deploy/cluster-api/api/cluster/v1alpha1.
```

**What you expected to happen**:

It just builds

**How to reproduce it (as minimally and precisely as possible)**:

Try to build it
```
go build .
```

**Anything else we need to know?**:

Originally reported by @mstemm trying to add a command https://github.com/falcosecurity/falco/pull/826#issuecomment-539713849

Also related to Go modules support #13 

@kris-nova believes this is because we are importing kubicorn packages. It uses old kubernetes dependencies that don't match the other kubernetes packages we use.

 I agree this could be the root cause, see for example: https://github.com/falcosecurity/falcoctl/blob/a0847a6aac8aecd4cd6258a3d6cef4110072aaf0/cmd/deleteFalco.go#L24

**Comment by Issif** [comment]
`kubicorn` uses `k8s.io/kube-openapi/cluster-api/api/cluster/v1alpha1`as dependency but it doesn't exist anymore. See : https://github.com/kubicorn/kubicorn/blob/master/Gopkg.lock#L824

`cluster-api` API of k8s is now in `v1alpha2` state : https://github.com/kubernetes-sigs/cluster-api/tree/master/api/v1alpha2
