### ISSUE TITLE
falcoctl issue as Kubernetes cluster doesn't have access to internet

### ISSUE THREAD

**Issue by blequell** [falcosecurity/falcoctl#264]
Hello,
Since Falco runs in release 0.34 I am no more able to install this tools due to falcoctl issue.
Indeed, falcoctl is expecting connectivity to Internet to get its own index.yaml while my cluster doesn't have access to it.
Do you have any idea to troubleshoot this issue as in go packages I only found url to be provided for this parameter.
I am using helm.
Thanks

**Comment by alacuku** [comment]
Hi @blequell, you can disable the falcoctl tool when deploying the Falco. Here you will find what you need in order to deploy Falco without `falcoctl` tool: https://github.com/falcosecurity/charts/blob/master/falco/BREAKING-CHANGES.md

**Comment by blequell** [comment]
Hi @alacuku,
it works.
Thanks for your quick reply.

**Comment by alacuku** [comment]
Great! Feel free to close the issue if there are no other problems.

**Comment by blequell** [comment]
done
