### ISSUE TITLE
How to build a private falco artifact

### ISSUE THREAD

**Issue by cui3093** [falcosecurity/falcoctl#267]
Is there any document can introduce me a way to build a private artifact for falcoctl?
**What would you like to be added**:

**Why is this needed**:
I have the case that the servers can not communicate with Internet in private environment.

**Comment by alacuku** [comment]
Hi @cui3093, if you are running Falcoctl in an air-gapped environment the best solution would be to store the `artifacts` in your own private registry and configure `falcoctl` to use that registry.

**Comment by cui3093** [comment]
@alacuku , thank you for your reply. Your advice is really helpful. But could you give me a tutorial to do that?

**Comment by alacuku** [comment]
Hi @cui3093, this article covers how to create artifacts(rules) and publish them to a OCI registry: https://falco.org/blog/gitops-your-falco-rules/. It covers the falco rules, but can be applied to the plugins too.

**Comment by maxgio92** [comment]
Hey @cui3093, can we considered this issue complete?
