### ISSUE TITLE
falcoctl via proxy

### ISSUE THREAD

**Issue by zenhighzer** [falcosecurity/falcoctl#290]
Hi, 

is there a way to tell falcoctl to use a proxy? 

We configured the proxy systemwide with /etc/environment: 

```
HTTP_PROXY="http://proxy:8080"
HTTPS_PROXY="http://proxy:8080"
http_proxy="http://proxy:8080"
https_proxy="http://proxy:8080"
```
syslog says:
```
ERRO: unable to fetch index "falcosecurity" with URL "https://falcosecurity.github.io/falcoctl/index.yaml": cannot fetch index: Get "https://falcosecurity.github.io/falcoctl/index.yaml": dial tcp 185.199.109.153:443: i/o timeout
```

But wget/curl https://falcosecurity.github.io/falcoctl/index.yaml works fine: 

```
$ curl https://falcosecurity.github.io/falcoctl/index.yaml 
- name: application-rules
  type: rulesfile
  registry: ghcr.io
  repository: falcosecurity/rules/application-rules
  description: Application rules
  home: https://github.com/falcosecurity/rules/blob/main/rules/application_rules.yaml
  keywords:
    - application-rules
  license: apache-2.0
[...]

```

**Comment by alacuku** [comment]
Hi @zenhighzer, `falcoctl` supports proxies out of the box. The error seems to be related to timeout issues. The `http clients` used in `falcoctl` sets the timeout to 30 seconds.

**Comment by zenhighzer** [comment]
Hi, 
I installed falco via APT and the "falcoctl-artifact-follow.service" throws this error in syslog. I just added to the 

/etc/systemd/system/falcoctl-artifact-follow.service.d/override.conf: 

```
[Service]
Environement=HTTP_PROXY=http://proxy:8080
Environement=HTTPS_PROXY=http://proxy:8080
```

Now it works... I dont think this is a timeout-problem. 
Best Regards

**Comment by zenhighzer** [comment]
@alacuku 

Yes, i think you can close this issue. 

Thank you and Best Regards
