### ISSUE TITLE
How can use the FALCOCTL_ARTIFACT_NOVERIFY env variable

### ISSUE THREAD

**Issue by ChauAnhTuan** [falcosecurity/falcoctl#328]
**What happened**: The falcoctl still verify image when I set FALCOCTL_ARTIFACT_NOVERIFY = true or null

**What you expected to happen**: I don't want verify image

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by alacuku** [comment]
Hi @ChauAnhTuan, if I run the following command it works as expected: 
```bash
FALCOCTL_ARTIFACT_NOVERIFY=true falcoctl artifact install k8saudit --plugins-dir=./
```

Please share how you are setting the env variable and the output of the command.

**Comment by LucaGuerra** [comment]
Alternatively, you can use the `--no-verify` flag in the CLI, but please let us know if you still have issues with the env variable.
