### ISSUE TITLE
Use apps/v1 instead of apps/v1beta2

### ISSUE THREAD

**Issue by oke-py** [falcosecurity/falcoctl#33]
**What would you like to be added**:

`apps/v1` should be used instead of `apps/v1beta2`.

e.g.
https://github.com/falcosecurity/falcoctl/blob/master/pkg/kubernetes/falco.go#L26

**Why is this needed**:

In k8s v1.16 `apps/v1beta2` is deprecated and removed.
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

**Comment by oke-py** [comment]
@leodido I'd like to, but I'm not sure how to make sure it works. I won't submit a PR.

**Comment by tylerauerbeck** [comment]
@leodido If this is still an issue, I wouldn't mind giving this a shot.
