### ISSUE TITLE
Extend falcoctl to build falco kernel probe 

### ISSUE THREAD

**Issue by natchaphon-r** [falcosecurity/falcoctl#34]
**What would you like to be added**:
A utility provided by falcoctl to install kernel probe for the OS the command is executed on. The command can be run before running a slim or minimal falco container.

**Why is this needed**:
- Falco does not pre-build kernel probe for all distributions/kernels
- See discussion in https://github.com/falcosecurity/falco/issues/890

**Comment by leodido** [comment]
Thanks for reporting what we discussed during the today's meeting. :)

Aside from this option I proposed today, in the next days we'll probably
propose another option too to approach this need.

Would be awesome if you could contribute this command anyway!

**Comment by leogr** [comment]
driverkit could be used to build the kernel module/eBPF probe for all distribution, I will start working on integrating it into falcoctl soon: https://github.com/falcosecurity/falcoctl/issues/81

Furthermore, the kernel module can be easily installed in [this way](https://github.com/falcosecurity/driverkit/issues/23), and I think `falcoctl` could to that for the user :)

/assign

**Comment by leogr** [comment]
Not a `falcoctl` responsibility anymore.
