### ISSUE TITLE
Refactor the CLI core to support common processes and actions for features like TLS and rules

### ISSUE THREAD

**Issue by kris-nova** [falcosecurity/falcoctl#44]
**What would you like to be added**:

Following a meeting at Kubecon, we began to explore the way that `falcoctl` is currently architected.
For user experience, and programming ease we would like to propose the following structure to the project.

We will began to look at the various pieces of  of `falcoctl` as **procceses**.

These **processes** represent features that we would like `falcoctl` to support. Each **process** will have a standard set of **actions**.

This standardizes the CLI tool, and improves user experience. This also allows us to begin defining **processes** to fit a common `interface{}` that we can call the `Processor{}` interface. 

This allows us to write generic code to initialize, and operate on valid `Processor`'s. By default `falcoctl` would attempt to operate remotely in a Kubernetes cluster, but could be overridden to perform the same logic locally using a `--local` flag. 

The parlance would be

```
falcoctl <process> <action>
```

Some basic examples would look like the following

```
# Generate and install TLS material in Kubernetes
falcoctl tls install 

# Generate and install TLS material locally in a directory like /etc/falco/certs
falcoctl tls install --local

# Install a new rule in Kubernetes from a valid Falco rules repository
falcoctl rule install <rule-string>

# Install a new rule locally in a directory like /etc/falco/rules from a valid Falco rules repository
falcoctl rule install <rule-string> --local
```

In this form, we can create methods for the various common **actions** 

 - install (create)
 - get (read)
 - update (update)
 - remove (delete) 

**Why is this needed**:

To improve user experience and standardize our code

**Comment by kris-nova** [comment]
Note this would help us with our work with the Cloud Native Security Hub at securityhub.dev

We can begin to explore building out **processes** and **actions** for rules such as

```
falcoctl rule install
falcoctl rule delete
falcoctl rule update
falcoctl rule get
falcoctl rule new
falcoctl reload
```

**Comment by leodido** [comment]
Perfect.

Only one nitpick: is “process” the word we want ? I would personally prefer something like “concept” or “area”.

Also, should we open other proposals/issues for other topics we discussed?
Namely the error management and the interactive mode

**Comment by Issif** [comment]
> Only one nitpick: is “process” the word we want ? I would personally prefer something like “concept” or “area”.
> 

I propose `context`, for example :
- tls : CA/key/cert generation
- probe : Install probe from S3 ou by `make`. We can either check is correct probe is on S3.
- rule : Install/Update/Delete rule(s) from Hub
- config : Apply configuration to Falco (with future API I guess)
- events : live stream of events through gRPC

**Comment by kris-nova** [comment]
Yes @leodido please open issues for them and link them here

**Comment by kris-nova** [comment]
@Issif @leodido regarding `context`

I think context is great, and I am sure others would agree. The reason I suggested `process` was so we could have a friendly interface name. The Go naming convention says

> By convention, one-method interfaces are named by the method name plus an -er suffix or similar modification to construct an agent noun: Reader , Writer , Formatter , CloseNotifier etc

Link: https://golang.org/doc/effective_go.html

So if we are okay with calling them `context`/`contexts` and calling the interface `contexter` or `contextable` that works for me!

Just ideas to think about.

**Comment by Issif** [comment]
👍 for `contexter`

**Comment by Kaizhe** [comment]
Can we have `falcoctl install rule -f <falco_rule_sinpet.yaml>` so that I don't need even install falco locally.

**Comment by brainsnail** [comment]
I think there are a couple of open issues around refactoring (https://github.com/falcosecurity/falcoctl/issues/57, ) - would y'all want to wait for those to be in a merged or completed state prior to moving forward with this or do you think it could be done concurrently?
