### ISSUE TITLE
Proposal: Automatic required engine version parsing for config layer of rules artifacts

### ISSUE THREAD

**Issue by Lowaiz** [falcosecurity/falcoctl#441]
**What would you like to be added**:
- a automatic parsing and setting of requirements (mainly required engine version) for rulesfile when pushing a rules file to a registry
  - the parsing of engine version is already implemented within rules repo, [here](https://github.com/falcosecurity/rules/blob/main/build/registry/requirements.go#L41)

**Why is this needed**:
- To avoid setting manually requirements when building and pushing a rules artifact. 
- The use case targeted is more or less a copy of official rules artifacts to a private OCI registry, keeping the config layer, so a copy with `crane`/`gcrane` to the private registry is sufficient for me (you might want to add a copy feature to registry command to avoid using third party tool, but I'm fine with that atm) but having this parsing could be a good feature to start writing custom rules files, and maybe centralize config OCI layer manipulation inside `falcoctl` repo.

**Comment by alacuku** [comment]
Hi @Lowaiz, falcoctl can now parse the requirements and dependencies from rulesfiles in yaml format. #467

**Comment by Lowaiz** [comment]
Gonna test that this week, thanks!
