### ISSUE TITLE
Make falcoctl containers available through Amazon ECR

### ISSUE THREAD

**Issue by portswigger-tim** [falcosecurity/falcoctl#443]
**What would you like to be added**: a falcoctl image in ECR Public, other falco images are available there. 

**Why is this needed**: Helps some people avoid docker hub limitations.

**Comment by alacuku** [comment]
Hi @portswigger-tim, the falcoctl images are now available in ECR Public: https://gallery.ecr.aws/falcosecurity/falcoctl.

**Comment by portswigger-tim** [comment]
Amazing! Thanks @alacuku x
