### ISSUE TITLE
Creation of AuditSink isn't idempotent

### ISSUE THREAD

**Issue by tylerauerbeck** [falcosecurity/falcoctl#47]
**What happened**:

According to the code comments [here](https://github.com/falcosecurity/falcoctl/blob/master/pkg/kubernetes/falco.go#L96-97):
```
<snip>
// Install is an idempotent installer for Falco in Kubernetes. By design if a resource already exists, we log it
// and move on with installing the others.
</snip>
```
However I get the following error if the AuditSink already exists:

`Fatal error: auditsinks.auditregistration.k8s.io "falco-audit-sink" already exists`

**What you expected to happen**:

I would expect to receive a message similar to the others when they already exist.. something like:

`AuditSink already exists: falco-audit-sink`

**How to reproduce it (as minimally and precisely as possible)**:

```
falcoctl install falco
falcoctl install falco
```

After the second run, you should see the error message

**Anything else we need to know?**:

**Comment by kris-nova** [comment]
This is a good issue, and in general the library we use to install Falco in Kubernetes is very hard-coded and needs some love.

**Comment by ndhanushkodi** [comment]
I'd like to work on this 
/assign

**Comment by kris-nova** [comment]
Also it looks like `falcoctl delete` doesn't remove all the resources that were installed - so we should probably look at that as well
