### ISSUE TITLE
Failed to verify certificate: x509 on falcoctl-artifact-install

### ISSUE THREAD

**Issue by mertomert** [falcosecurity/falcoctl#483]
**Describe the bug**

I stood up Falco with helm on rke2 cluster. Then I added new worker nodes, but I get the error "falcoctl-artifact-install init container failed to verify certificate: x509: certificate is valid for *.xxx.local, not falcosecurity.github.io".

**Screenshots**

![image](https://github.com/falcosecurity/falco/assets/22898980/641bf84f-cdce-4b95-8a2d-ee32fb0d7ebe)

**Environment**

- Falco version:
0.37.1
- System info:
v1.26.0+rke2r1           5.15.0-72-generic   containerd://1.6.12-k3s1
- OS:
Ubuntu 22.04.2 LTS
- Installation method:
helm

**Comment by LucaGuerra** [comment]
We've had a similar request due to an issue with proxy configuration: https://github.com/falcosecurity/falco/issues/3119 . Can you verify your proxy config, or try to `curl` from the pod and see if it's a problem with falcoctl or with your cluster configuration?

**Comment by leogr** [comment]
any updates on this? :thinking:
