### ISSUE TITLE
Command to search probes

### ISSUE THREAD

**Issue by leodido** [falcosecurity/falcoctl#51]
**What would you like to be added**:

Following a discussion on the open slack I had the idea of introducing a command to search probes (by platform, by version etc).

Eg., falcoctl search probes

Not yet sure about the nomenclature. It should be a command name that matches the future structure of this tools (see #44)

**Why is this needed**:
It can be useful to have a way to detect whether a probe for a given Falco version exists or not and behave accordingly (eg update Falco or not).

**Comment by Issif** [comment]
I had this exact issue in mind when I started to work on : 

https://thomas.labarussias.fr/falco-probes/

My idea was to provide json files that can be consumed by any extra tool, like `falcoctl`.

Here an example : https://thomas.labarussias.fr/falco-probes/data/0.17.1.json

The CI which build kernel modules should create them.

**Comment by fntlnz** [comment]
I think that this is outdated now that we made a decision on the service right ?

Referring to this: https://github.com/falcosecurity/falco/issues/1027

Proposal not yet done.

**Comment by Issif** [comment]
👍

**Comment by leogr** [comment]
As discussed recently, I believe this does not apply anymore. Feel free to re-open it if I misunderstood the scope of this issue.
