### ISSUE TITLE
Probe loader should be renamed

### ISSUE THREAD

**Issue by kris-nova** [falcosecurity/falcoctl#53]
**What happened**:

Doing some homework on building an `eBPF` probe loader into `falcoctl` and I checked out the `probeloader` package.

It's currently using syscall `313` which is for loading kernel modules (not eBPF probes)

**What you expected to happen**:

Maybe we should call the package `kernelmoduleloader`?

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by AnishShah** [comment]
I would like to work on this. 

/assign
