### ISSUE TITLE
Standardize falcoctl Go structure

### ISSUE THREAD

**Issue by kris-nova** [falcosecurity/falcoctl#57]
**What would you like to be added**:

Can we please go through the `/cmd` and `/pkg` directories and do a quick refactor to idiomatic go practices? Looks like there is some concern with naming files and packages, and we want to make sure we use best practices here.

**Why is this needed**:

The project is still young, and we should get it started on the right foot.

**Comment by sureshpalemoni** [comment]
Submitted this PR for the /cmd directory https://github.com/falcosecurity/falcoctl/issues/57

**Comment by sureshpalemoni** [comment]
https://github.com/falcosecurity/falcoctl/pull/63 - refactored only cmd directory

**Comment by sureshpalemoni** [comment]
https://github.com/falcosecurity/falcoctl/pull/68

**Comment by sureshpalemoni** [comment]
@kris-nova Can this issue be closed?

**Comment by leogr** [comment]
> /close

Done
