### ISSUE TITLE
Add support for S3 index storage backend 

### ISSUE THREAD

**Issue by brennoo** [falcosecurity/falcoctl#606]
**What would you like to be added**:  
I would like to have a new index fetcher for AWS S3 backend

**Why is this needed**: 
Our workloads run mainly on AWS and that would simplify the access for a private index stored in S3

if this sounds reasonable I'm happy to submit a PR

**Comment by alacuku** [comment]
Hi @brennoo, a contribution like that would be great! Please feel free to submit a PR for this feature.
