### ISSUE TITLE
Falcoctl Commands

### ISSUE THREAD

**Issue by kris-nova** [falcosecurity/falcoctl#65]
# History

This project was originally proposed here in https://github.com/falcosecurity/falco/issues/811

The purpose of this project is to support and encapsulate commonly used logic for The Falco Project.

# What is a Falcoctl command?

A command consists of three things. 

 - An action
 - A subject
 - A target  

For instance the following CLI command

```bash
$ falcoctl install tls --local
```

Would yield:

 - Install (action)
 - TLS (subject)
 - Local (target) 

Note that we would like `falcoctl` to default to Kubernetes as the default target such that the following two commands would be identical commands. 

```bash
$ falcoctl install tls
$ falcoctl install tls --kubernetes
```

--- 

# Commands

Here are commands I think the project should support.

For each of these commands, we will need the following support

### An idiomatic `.go` starting point in the `/cmd` directory

Following the naming convention where 

```bash
falcoctl install tls
```

should be named

```
install_tls_<os>.go
install_tls_linux.go
install_tls_windows.go
install_tls_freebsd.go
```

### An exposed package that can be vendored as a library

The point of the `/pkg` directory is create libraries we can use in other places of the project, or even for other projects/users to consume. So write the code as complete as possible, and make the libraries as modular as possible. A good example of writing consumable libraries is [in the Kubernetes code base itself](https://github.com/kubernetes/kubernetes/tree/master/pkg).

The `/cmd` directory should just define CLI flags/options and inject the configuration into various libraries found in the `/pkg` directory. 

---

# Features

Below is a list of features that we think `falcoctl` should support. These are open for discussion, and are not a complete list. This is just a starting point. 

If you would like to fix/refactor/create/support any of these commands please open up an issue for the one you would like to work on and `/assign` it to yourself. 

---
Create TLS material for Falco on the same filesystem that `falcoctl` is installed on.
```
falcoctl install tls --local 
```

---
Create TLS material for Falco in Kubernetes and also configure Falco to look for the newly created secrets
```
falcoctl install tls --kubernetes 
```

---
Idempotent install of Falco on the local filesystem
```
falcoctl install falco --local
```

---
Idempotent install of Falco in Kubernetes
```
falcoctl install falco --kubernetes 
```

---
Install a new Falco rule on the local file system
```
falcoctl install rule --local 
```

---
Install a new Falco rule in Kubernetes
```
falcoctl install rule --kubernetes 
```

**Comment by kris-nova** [comment]
If folks have thoughts/ideas for other commands please begin documenting them here in the same fashion as above.

Also - reminder if you would like to start refactoring or creating new commands to just open up an issue for whatever command you are interested in working on so we can track it.

Happy hacking :)

**Comment by kris-nova** [comment]
Also please read https://github.com/falcosecurity/falco/issues/1024#issuecomment-578566826 

After looking at the user experience of a `--local` and a `--kubernetes` flag it might make sense to define an environmental variable such as

```bash
export FALCOCTL_ENV=local
export FALCOCTL_ENV=kubernetes
```

Or even add documentation to do something like this

```bash
alias fl="falcoctl --local"
alias fk="falcoctl --kubernetes"
```

So that

```bash
fl install tls  #Install TLS locally
fk install tls  #Install TLS in Kubernetes

```

**Comment by joshuabezaleel** [comment]
Hi @rajibmitra , I want to have a shot on this if it's okay with you and there are some commands left to be implemented. From the "Features" section above, which of the feature requests are you currently implementing or are you implementing all of them? 

Thank you very much :slightly_smiling_face:

**Comment by Issif** [comment]
Install `falcosidekick` on the local file system

```
falcoctl install sidekick --local 
```

Install `falcosidekick` in Kubernetes

```
falcoctl install sidekick --kubernetes
```

😃

**Comment by rajibmitra** [comment]
Hi @joshuabezaleel I have assigned this to you , pelase go ahead and raise a PR. I would love to take a look.If you got any questions feel free to ping me in slack.

**Comment by ameukam** [comment]
Hi @kris-nova, I'm not sure how `falcoctl install` works. I would like to suggest: 
```console
falcoctl upgrade falco --kubernetes
```

**Comment by leogr** [comment]
I would like to suggest:
- `--target=kubernetes`
- `--target=local`
It would be clearer and can simplify the addition of further targets.
WDYT?
