### ISSUE TITLE
Implementing "falcoctl install falco --local" using the process interface

### ISSUE THREAD

**Issue by mohitgoyal2011** [falcosecurity/falcoctl#67]
**What would you like to be added**:
Base on #65 and #66, this feature request is to implement falcoctl install falco --local. Here are the code changes planned :
  - new go file called install_falco_local.go will be created
  - this will implement the interface present in the /process
 
**Why is this needed**:
  - To implement one of the commands mentioned in #65 

**About me**
 - I am a software developer looking to get some experience with cloud/container security. I am quite new to Falco (thought have compiled from source :D) and newish to Golang. Will update the code changes mentioned above after taking a closer look at the code and how to go about it.

**Comment by mohitgoyal2011** [comment]
\assign me

**Comment by kris-nova** [comment]
Please make sure you review https://github.com/falcosecurity/falcoctl/issues/47

To make sure we are collaborating on effort for this

**Comment by kris-nova** [comment]
Also adding this to the call next wed - there might be some discussion about how we handle eBPF probes and kernel modules :wink:

**Comment by kris-nova** [comment]
Also check out this issue I opened #1024

There is a lot to consider here, and I think having the operating system logic to install Falco should live in a place that users of the operating system would expect it to be.

Note: If we had Falco supported in many different operating systems natively, building a Falco container would be as simple as doing something like apt-get install falco

Furthermore all falcoctl would have to do would be exactly the same thing apt-get install Falco

**Comment by mohitgoyal2011** [comment]
So, I am looking at the current code and the way the installation is being done in the bash script. So, across the distros, I think there are 4 steps to every filesystem installation : 
1. Adding the Sysdig public key
2. Then adding the falco repo and enabling it
3. Installing kernel headers using the package manager
4. Install Falco using the package manager
(I kind of listed down the logs in the script)
I feel depending on the package managers in the respective operating systems makes sense as dependencies of dependencies keep changing. The falcoctl command would essentially be a much more standardized version of the bash script that should be way more robust and always exit gracefully. The only issue with this is that we will be running shell commands in falcoctl unless golang and apt-get have an API somewhere (I found a thin wrapper that might help keep our code readable - https://github.com/arduino/go-apt-client) 

Another way of going about this is probably implementing the debian/rpm pre/postinstall scripts ourselves. But that seems like duplication of effort without the reliability of yum/apt-get.

What else did you have in mind ? Do you think we should handle installing the kernel module separately rather than go the package manager route ?

**Comment by q2dg** [comment]
Note Falco scripted install (https://falco.org/docs/installation/#scripted) fails miserably in Fedora systems

**Comment by leogr** [comment]
> Note Falco scripted install (https://falco.org/docs/installation/#scripted) fails miserably in Fedora systems

Hey @q2dg 
Could you report your issue in the [falco-website](https://github.com/falcosecurity/falco-website) and add more context, please?

**Comment by leogr** [comment]
As discussed recently with the community, we don't want to support further Falco installation methods other than the official ones. Thus, I believe this issue should be closed.
See #95
