### ISSUE TITLE
Command for a hot-reload (dynamic reload) of Falco

### ISSUE THREAD

**Issue by kris-nova** [falcosecurity/falcoctl#69]
**What would you like to be added**:

Right now you can send `SIGHUP` to Falco to trigger a hot reload. 

This will re-load rules, and configuration without actually stopping the process. 

**Why is this needed**:

User experience for easily adding/mutating rules and config on the fly.

**Comment by AnishShah** [comment]
I can work on this.

/assign

**Comment by AnishShah** [comment]
Hi Kris. Since Falco runs as DaemonSet, do we want to just delete the pods scheduled by the DaemonSet? It will automatically schedule a new pod. I'm not sure how to send SIGHUP to a Pod.

**Comment by leogr** [comment]
Since we agreed on install Falco (see #95 ) we will need to implement the config hot reload in a different way.
