### ISSUE TITLE
Add Prow for falcoctl with gcp 

### ISSUE THREAD

**Issue by markyjackson-taulia** [falcosecurity/falcoctl#7]
This work will be done with me and @rajibmitra 
Umbrella tasks are:
- [ ] Add @rajibmitra to google cloud
- [ ] Add integration with FalcoCTL to prow
- [ ] Document

**Comment by rajibmitra** [comment]
Thanks @markyjackson-taulia  for creating and assigning this issue. Lets get this done. 👍

**Comment by rajibmitra** [comment]
@markyjackson-taulia can we have a prow instance like https://prow.falcoctl.io  like k8s has https://prow.k8s.io/

**Comment by fntlnz** [comment]
I have a domain called `falcosecurity.dev` - I think we might like to use that one !

**Comment by rajibmitra** [comment]
great @fntlnz  lets have https://prow.falcosecurity.dev , and under this we can map all the prow jobs per repository.

**Comment by leodido** [comment]
Prow instance have to be for the whole `falcosecurity` organization. The same way it is now (PTAL https://github.com/falcosecurity/test-infra).

**Comment by markyjackson-taulia** [comment]
@falcosecurity/falcoctl-maintainers I will try to get this out today or tomorrow. I want to work with @rajibmitra

**Comment by markyjackson-taulia** [comment]
See issue https://github.com/falcosecurity/test-infra/issues/59

**Comment by fntlnz** [comment]
Sorry @markyjackson-taulia the title is confusing me. Should be gcp and not grpc right ?

**Comment by markyjackson-taulia** [comment]
Correct @fntlnz
