### ISSUE TITLE
Add command to obtain Falco version

### ISSUE THREAD

**Issue by kris-nova** [falcosecurity/falcoctl#71]
**What would you like to be added**:

```
falcoctl version
```

This would similar to `kubectl version` and work with this new API https://github.com/falcosecurity/falco/pull/872

**Why is this needed**:

**Comment by abd2312** [comment]
Hi @kris-nova  , I want to work on this if it's okay with you.

**Comment by leodido** [comment]
Hey Kris, this should be something like (imho): 

```console
falcoctl falco version
```

This because the Falco Version API returns the Falco version.

**Comment by RajatVaryani** [comment]
@leodido @kris-nova Is this open for contribution?
