### ISSUE TITLE
Smart Install

### ISSUE THREAD

**Issue by kris-nova** [falcosecurity/falcoctl#73]
**What would you like to be added**:

Right now there are many concerns with installing Falco. 

 - A DaemonSet does not schedule Falco on the master (this is very bad)
 - Falco needs to run as a privileged user
 - There are concerns with different versions of Kubernetes (API incompatibility)
 - Configuring outputs
 - Configuring Kubernetes audit

Can we please start to solve the install step by first looking what version of Kubernetes we are running, so that we can install the DaemonSet accordingly?

We would need to vendor different versions of `client-go` and probably have an interface for the install that each version can implement. 

I think we should support `1.13` and everything after. 

**Why is this needed**:

Because runtime security is a real problem.

**Comment by ndhanushkodi** [comment]
I'd like to work on this :)
/assign

**Comment by ndhanushkodi** [comment]
I'd like to unassign myself and focus on learning more about core falco
/unassign

**Comment by leogr** [comment]
Furthermore, I believe we should clarify more the goals that `falcoctl` wants to achieve before implementing the right installation strategy. So I'd propose to close this issue in favor of #86 

@ndhanushkodi feel free to share your thoughts on this topic anyway! We're still working on that and every opinion counts :)
