### ISSUE TITLE
Add github actions for falcoctl automation. 

### ISSUE THREAD

**Issue by rajibmitra** [falcosecurity/falcoctl#8]
This is just a suggestion. Please let me know your thoughts @falcosecurity/falcoctl-maintainers

**Comment by Issif** [comment]
For code coverage, I pretty like [coverall](https://coveralls.io/), github actions for units tests and coverall for code coverage.

**Comment by leodido** [comment]
I would prefer to not have github action as discussed during our last office hours.

Since we have prow in place we can create prow jobs for testing and coverage purposes. Also we are in the process of having a dedicated CI/CD infrastructure for this whole organization and projects :)

**Comment by rajibmitra** [comment]
Okay @leodido  , closing this issue now.
