### ISSUE TITLE
CLI tests

### ISSUE THREAD

**Issue by leodido** [falcosecurity/falcoctl#87]
**What would you like to be added**:

Since `falcoctl` starts to grow, it would be a good thing to also test its CLI.

This can be done in the same way I did for `driverkit`, [here](https://github.com/falcosecurity/driverkit/pull/49).

**Why is this needed**:

The goal is to be able to introduce new flags, new sub-commands, etc. without breaking the existing ones.

**Comment by leogr** [comment]
I agree, but we may need to change some command interfaces, so I'd wait until https://github.com/falcosecurity/falcoctl/issues/86 has been done.
