### ISSUE TITLE
Add readme file for falcoctl.

### ISSUE THREAD

**Issue by rajibmitra** [falcosecurity/falcoctl#9]
Let us add one readme file for falcoctl with all the details especially the arguments. 
cc @falcosecurity/falcoctl-maintainers

**Comment by markyjackson-taulia** [comment]
/assign @markyjackson-taulia @rajibmitra 
I am going to assign this to both of us @rajibmitra. Would make sense to start a public google doc and work off of that?

**Comment by rajibmitra** [comment]
Sure, I like the idea.

**Comment by markyjackson-taulia** [comment]
@rajibmitra I created this folder https://drive.google.com/drive/folders/1z5-TIZRijoxVJI0zoVbkhv6sGA8xMWxW?usp=sharing in google drive. In it is the start of our document for the readme. You should have edit rights
