### ISSUE TITLE
Falco with Kubernetes

### ISSUE THREAD

**Issue by leogr** [falcosecurity/falcoctl#95]
**What would you like to be added**:
As discussed several times, we would like to use `falcoctl` as the official installation method for running Falco *with* Kubernetes. 

**Why is this needed**:

As explained [here](https://github.com/falcosecurity/falco/issues/1114#issuecomment-604580503), Falco is NOT a Kubernetes application. Thus it should not just be deployed in a cluster like any other Kubernetes application, but it has to be installed at Linux level (next to Kubernetes).

That being said, `falcoctl` would be responsible for installing Falco on the nodes by using the Kubernetes API and configuring it in such a way that it works well with Kubernetes. 

# Proposal 

### K8s Cluster

- Download static binary `falcoctl`
- Run `falcoctl install falco --target=kubernets`
    - `falcoctl` connects to the cluster as like `kubectl` does
    - Install Falco (and the drivers) on nodes
- Run `falcoctl install tls --target=kubernetes`
    - `falcoctl` connects to the cluster as like `kubectl` does
    - Generates and install TLS materials on nodes
- ...

### Single host
- SSH into the targeted host
- Use the official method to install Falco
- Download static binary `falcoctl`
- Run `falcoctl install tls --target=local`
    - Locally generates and install TLS materials
- ...

**Notes**:
- `--target=kubernetes` can be omitted if Kubernetes is the default target 
- We do not really need a separate command to install the drivers, Falco installation should always include the driver installation.

### Versioning

1. Users should be able to choose the version of Falco 
2. `falcoctl` should be able to interact with different versions of Kubernetes (eg. setting the correct API version on resources, see #72)

Minimim supported versions:
- Falco: 0.23 
- Kubernetes: _TBD_ 1.13?

## Upstreams

`falcoctl` should rely on the following officially supported upstreams.
| Name | Versioned | Upstream |
| -------- | -------- | -------- |
| falco packages (deb, rpm, bin)    | Y | https://dl.bintray.com/falcosecurity/bin/ |  |
| driverloader    | Y | https://hub.docker.com/r/falcosecurity/driverloader |

**Note** - the `driverloader` image is needed only when Falco has been installed by using the binary package 

## Tasks

Tasks comparison between `local` and `kubernetes` targets.

| Action | Subject | `local` | `kubernetes` |
| -------- | -------- | -------- | -------- |
| **install** | falco  | *Not to be implemented (users should use official installation methods)* | On each node, install Falco with the driver and configure it to work with K8s |
| **remove**  | falco  | *Same as above* | Uninstall Falco and the driver from each node |
| **install** | tls    | Generate TLS material into local path | Generate TLS material and copy them into each node |
| **remove**  | tls    | Delete TLS material from local path      | Delete TLS material from each node  |
| **config set**  | *something* | Modify the local `falco.yml`      | Modify `falco.yml` on each node |
| **generate**  | events | Download and run the event-generator (or do not implement it locally)      | Deploy the event-generator on each node |

**Notes**:
 - The above table includes just some examples, other tasks might be needed
 - Falco will run on the Linux level in all cases
 - For Kubernetes, some tasks (eg. the Falco installation) will work by privilege escalating in the cluster.

**Comment by nibalizer** [comment]
Thanks for working on this! I appreciate my use case being kept alive.

Re versions: [IBM Cloud defaults](https://cloud.ibm.com/docs/containers?topic=containers-cs_versions#version_types) to 1.16 and considers 1.14 and below deprecated. So from my perspective you're good to start as high as 1.16. If I'm reading [the upstream docs](https://kubernetes.io/docs/setup/release/version-skew-policy/) correctly, upstream kubernetes also stops support after 1.16 right now.

Possibly out of scope: what is the node lifecycle thinking? One nice thing about the daemonset model is it automatically configures any new nodes that join the cluster.

What is the thinking on upgrading? I think we'd all hope the package would do everything, but ...

Again possibly out of scope: When falco runs inside the kubernetes cluster, it uses a clusterrolebinding/clusterrole/serviceaccount - what's the plan when it's running next to a kubernetes cluster? Still need some material to auth to the k8s api I think as well. Is this set up by `falcoctl`?

**Comment by leogr** [comment]
> Thanks for working on this! I appreciate my use case being kept alive.
> 

You're welcome! :+1: 

> Re versions: [IBM Cloud defaults](https://cloud.ibm.com/docs/containers?topic=containers-cs_versions#version_types) to 1.16 and considers 1.14 and below deprecated. So from my perspective you're good to start as high as 1.16. If I'm reading [the upstream docs](https://kubernetes.io/docs/setup/release/version-skew-policy/) correctly, upstream kubernetes also stops support after 1.16 right now.

Good to know that

> Possibly out of scope: what is the node lifecycle thinking? One nice thing about the daemonset model is it automatically configures any new nodes that join the cluster.
> 

Good question. 

Since Falco will be installed on the Linux level there's no lifecycle here. Also, I'm assuming `falcoctl` has the simple responsibility to help a human in installing Falco next to K8s - not controlling the lifecycle (at least not atm).

Maybe we can add another layer later that runs into the cluster and take care of lifecycle (an operator?). Anyhow, I would think that once we have low-level tasks implemented, I would not add complexity that much in this layer.
In general, I would like to keep automation and orchestration separate. 
So yes, it's out of scope - but just atm! :)

> What is the thinking on upgrading? I think we'd all hope the package would do everything, but ...
> 

Same as above.

> Again possibly out of scope: When falco runs inside the kubernetes cluster, it uses a clusterrolebinding/clusterrole/serviceaccount - what's the plan when it's running next to a kubernetes cluster? Still need some material to auth to the k8s api I think as well. Is this set up by `falcoctl`?

Yes. `falcoctl` should set up everything to make Falco work with K8s nicely. Btw, I still need to dig into that.

Thank you for sharing your thoughts!!!
